### ISSUE TITLE
Should there be a leaf to enable proxy-arp globally?

### ISSUE THREAD

**Issue by rgwilton** [rgwilton/arp-yang-draft#2]
The model currently has a global leaf to enable proxy-arp on all interfaces, but this seems a strange thing to do.  E.g. on a router, I don't think that you would want to enable proxy-arp on a management port.  I think that it is better to explicitly enable proxy-ARP on each interfaces for which it is required, that inherently feels more secure.

**Comment by lana-wu** [comment]
OK, I agree to remove the global leaft of proxy-arp.
