### ISSUE TITLE
Should the model really support "proxy arp ALL"?

### ISSUE THREAD

**Issue by rgwilton** [rgwilton/arp-yang-draft#3]
The model defines two modes for proxy-arp: remote-only and all.  RFC 1027 explicitly disallows proxy-arp on behalf of other devices on the local subset, i.e. it only allows the option described as "remote only".

What is the use case as to why a device would want to reply to ARP requests on behalf of other devices on the same subnet?

**Comment by lana-wu** [comment]
I'd like to suggest to add some text like:
In the case of certain data center network virtualization, 
        as specified in An Architecture for Data-Center NVO3 
        [RFC 8014],  the proxy ARP can be extended
        to intercept all ARP requests, including source and target IP
        addresses in different subnets, and those ARP requests in the 
        same subnet, to suppress ARP handling .
